run:
	gcc -o insertion insertion_sort.c
	go build -o go-insertion insertion_sort.go
	g++ -o bubble bubble_sort.cpp
	go build -o go-bubble bubble_sort.go
	gcc -o selection selection_sort.c
	go build -o go-selection selection_sort.go

clean:
	rm -f insertion go-insertion bubble go-bubble selection go-selection
