run:
	gcc -o liner_search liner_search.c
	go build -o go-liner_search liner_search.go
	gcc -o binary_search binary_search.c
	go build -o go-binary_search binary_search.go
	gcc -o hash hash.c

clean:
	rm -f liner_search go-liner_search binary_search go-binary_search hash a.out
